server:
  port: 8901

spring:
  application:
    name: ProductService

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true

management:
  tracing:
    sampling:
      probability: 1.0

otlp:
  tracing:
    endpoint: http://localhost:9411/api/v2/spans
